### ISSUE TITLE
No runtime or distribution __version__ when installed from sdist

### ISSUE THREAD

**Issue by bollwyvl** [penguinolog/backports.cached_property#4]
Thanks for this package!

In trying to package something that has this package as a dependency, I'd like to verify its (many) dependencies with `pip check`. If a dependency on `backports.cached_property` carries any version info, it fails here, as the `METADATA` file shipped has the fallback value of `0.0.0`.

Would a PR be welcome that added a `__version__`? 

If so, is there a preference in how to add it? 

If there is no preference, I have an anecdotal experience: having had bad luck with other "elegant" approaches, the most stable form I have found is:
- check in a dumb `VERSION` text file, shipped in the module source folder
- at packaging time, read it from `setup.cfg` with the `file:` special key
- at runtime, read with the old-but-not-busted `pkgutil`... even works inside a `.zip`

Thanks again!

**Comment by penguinolog** [comment]
Fix version: 1.0.2

**Comment by bollwyvl** [comment]
Thank you so much!
