### ISSUE TITLE
Add comparison to stacked `@property` + `@lru_cache(maxsize=1)`

### ISSUE THREAD

**Issue by mara004** [penguinolog/backports.cached_property#8]
I wonder if `@property` + `@lru_cache(maxsize=1)` is a suitable alternative to emulate `@cached_property` on older python versions? How does it compare to `@cached_property`?

**Comment by penguinolog** [comment]
`cached_property` store cache in class instance and can be invalidated the same way as original implementation.
`lru_cache` storage is a bit different

**Comment by mara004** [comment]
> lru_cache storage is a bit different

different in what way?

**Comment by penguinolog** [comment]
Different in way to invalidate cache for example

**Comment by mara004** [comment]
Anything else?
